services:
  main:
    build: .
    entrypoint: [ "uv", "run", "./src/main.py" ]
    volumes:
      - ./src:/app/src
      - ${REPORT_DIR}:/app/report
      - ${DATASETS_DIR}:/app/datasets
      - ${LOGS_DIR}:/app/logs
      - ${EXP_CONFIG_DIR}:/app/exp_configs
    environment:
      - PYTHONPATH=/app/src
    env_file: .env

  run_paper_experiments:
    build: .
    profiles: [ "run_paper_experiments" ]
    entrypoint: [ "uv", "run", "./src/run_paper_experiments.py", "run", "paper_grid.yaml" ]
    volumes:
      - ./src:/app/src
      - ${DATASETS_DIR}:/app/datasets
      - ${LOGS_DIR}:/app/logs
      - ${EXP_CONFIG_DIR}:/app/exp_configs
    environment:
      - PYTHONPATH=/app/src
    env_file: .env

  generate_report:
    build: .
    profiles: [ "generate_report" ]
    entrypoint: [ "uv", "run", "./src/evaluate_notebooks.py" ]
    volumes:
      - ./src:/app/src
      - ${REPORT_DIR}:/app/report
      - ${DATASETS_DIR}:/app/datasets
      - ${LOGS_DIR}:/app/logs
      - ${EXP_CONFIG_DIR}:/app/exp_configs
      - ${LITERATURE_STUDY_DIR}:/app/literature_study
    environment:
      - PYTHONPATH=/app/src
    env_file: .env
